<a href="https://colab.research.google.com/github/sarasheth/DA_LAB/blob/main/DA_LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
import matplotlib.pyplot as plt

In [20]:
from google.colab import files
uploaded = files.upload();
data = pd.read_csv("HT_2013-2020.csv");
data

Saving HT_2013-2020.csv to HT_2013-2020 (1).csv

,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,COUNTY_NAME,REGION_NAME,POPULATION_GROUP_CODE,POPULATION_GROUP_DESC,OFFENSE_SUBCAT_ID,OFFENSE_NAME,OFFENSE_SUBCAT_NAME,ACTUAL_COUNT,UNFOUNDED_COUNT,CLEARED_COUNT,JUVENILE_CLEARED_COUNT
0,2016,MO0480600,Independence,NaN,City,MO,Missouri,West North Central,JACKSON,Midwest,2,"Cities from 100,000 thru 249,999",81,Human Trafficking,Commercial Sex Acts,2,0,2,0
1,2016,TX2201200,Fort Worth,NaN,City,TX,Texas,West South Central,PARKER; DENTON; TARRANT,South,1B,"Cities from 500,000 thru 999,999",82,Human Trafficking,Involuntary Servitude,1,0,0,0
2,2016,TX2270100,Austin,NaN,City,TX,Texas,West South Central,WILLIAMSON; TRAVIS,South,1B,"Cities from 500,000 thru 999,999",82,Human Trafficking,Involuntary Servitude,2,0,0,0
3,2019,NV0020100,Las Vegas Metropolitan Police Department,NaN,City,NV,Nevada,Mountain,CLARK,West,1A,"Cities 1,000,000 or over",81,Human Trafficking,Commercial Sex Acts,15,0,4,0
4,2017,AZ0070500,Chandler,NaN,City,AZ,Arizona,Mountain,MARICOPA,West,2,"Cities from 100,000 thru 249,999",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4412,2019,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",82,Human Trafficking,Involuntary Servitude,2,0,0,0
4413,2019,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",82,Human Trafficking,Involuntary Servitude,1,0,0,0
4414,2020,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
4415,2020,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
4416,2020,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",81,Human Trafficking,Commercial Sex Acts,1,0,0,0

In [21]:
data.head()

,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,COUNTY_NAME,REGION_NAME,POPULATION_GROUP_CODE,POPULATION_GROUP_DESC,OFFENSE_SUBCAT_ID,OFFENSE_NAME,OFFENSE_SUBCAT_NAME,ACTUAL_COUNT,UNFOUNDED_COUNT,CLEARED_COUNT,JUVENILE_CLEARED_COUNT
0,2016,MO0480600,Independence,NaN,City,MO,Missouri,West North Central,JACKSON,Midwest,2,"Cities from 100,000 thru 249,999",81,Human Trafficking,Commercial Sex Acts,2,0,2,0
1,2016,TX2201200,Fort Worth,NaN,City,TX,Texas,West South Central,PARKER; DENTON; TARRANT,South,1B,"Cities from 500,000 thru 999,999",82,Human Trafficking,Involuntary Servitude,1,0,0,0
2,2016,TX2270100,Austin,NaN,City,TX,Texas,West South Central,WILLIAMSON; TRAVIS,South,1B,"Cities from 500,000 thru 999,999",82,Human Trafficking,Involuntary Servitude,2,0,0,0
3,2019,NV0020100,Las Vegas Metropolitan Police Department,NaN,City,NV,Nevada,Mountain,CLARK,West,1A,"Cities 1,000,000 or over",81,Human Trafficking,Commercial Sex Acts,15,0,4,0
4,2017,AZ0070500,Chandler,NaN,City,AZ,Arizona,Mountain,MARICOPA,West,2,"Cities from 100,000 thru 249,999",81,Human Trafficking,Commercial Sex Acts,1,0,0,0

In [22]:
data.tail()

,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,COUNTY_NAME,REGION_NAME,POPULATION_GROUP_CODE,POPULATION_GROUP_DESC,OFFENSE_SUBCAT_ID,OFFENSE_NAME,OFFENSE_SUBCAT_NAME,ACTUAL_COUNT,UNFOUNDED_COUNT,CLEARED_COUNT,JUVENILE_CLEARED_COUNT
4412,2019,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",82,Human Trafficking,Involuntary Servitude,2,0,0,0
4413,2019,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",82,Human Trafficking,Involuntary Servitude,1,0,0,0
4414,2020,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
4415,2020,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
4416,2020,KY0370000,Franklin,NaN,County,KY,Kentucky,East South Central,FRANKLIN,South,8C,"Non-MSA counties from 10,000 thru 24,999",81,Human Trafficking,Commercial Sex Acts,1,0,0,0

In [23]:
data.isnull().sum()

DATA_YEAR                    0
ORI                          0
PUB_AGENCY_NAME              0
PUB_AGENCY_UNIT           4203
AGENCY_TYPE_NAME             0
STATE_ABBR                   0
STATE_NAME                   0
DIVISION_NAME                0
COUNTY_NAME                111
REGION_NAME                  0
POPULATION_GROUP_CODE        0
POPULATION_GROUP_DESC        0
OFFENSE_SUBCAT_ID            0
OFFENSE_NAME                 0
OFFENSE_SUBCAT_NAME          0
ACTUAL_COUNT                 0
UNFOUNDED_COUNT              0
CLEARED_COUNT                0
JUVENILE_CLEARED_COUNT       0
dtype: int64

In [24]:
data.size

83923

In [25]:
data.shape

(4417, 19)

In [26]:
data.describe()

,DATA_YEAR,OFFENSE_SUBCAT_ID,ACTUAL_COUNT,UNFOUNDED_COUNT,CLEARED_COUNT,JUVENILE_CLEARED_COUNT
count,4417.000000,4417.000000,4417.000000,4417.000000,4417.000000,4417.000000
mean,2017.884763,81.194476,2.173194,0.072674,0.837673,0.032601
std,1.843414,0.395841,3.128820,0.926374,2.069699,0.433354
min,2013.000000,81.000000,-1.000000,0.000000,0.000000,0.000000
25%,2017.000000,81.000000,1.000000,0.000000,0.000000,0.000000
50%,2018.000000,81.000000,1.000000,0.000000,0.000000,0.000000
75%,2019.000000,81.000000,2.000000,0.000000,1.000000,0.000000
max,2020.000000,82.000000,67.000000,47.000000,41.000000,19.000000

In [27]:
data.columns

Index(['DATA_YEAR', 'ORI', 'PUB_AGENCY_NAME', 'PUB_AGENCY_UNIT',
       'AGENCY_TYPE_NAME', 'STATE_ABBR', 'STATE_NAME', 'DIVISION_NAME',
       'COUNTY_NAME', 'REGION_NAME', 'POPULATION_GROUP_CODE',
       'POPULATION_GROUP_DESC', 'OFFENSE_SUBCAT_ID', 'OFFENSE_NAME',
       'OFFENSE_SUBCAT_NAME', 'ACTUAL_COUNT', 'UNFOUNDED_COUNT',
       'CLEARED_COUNT', 'JUVENILE_CLEARED_COUNT'],
      dtype='object')

In [28]:
data.dropna(inplace = True)

In [29]:
data.shape

(181, 19)

In [33]:
data.isnull().sum()

DATA_YEAR                 0
ORI                       0
PUB_AGENCY_NAME           0
PUB_AGENCY_UNIT           0
AGENCY_TYPE_NAME          0
STATE_ABBR                0
STATE_NAME                0
DIVISION_NAME             0
COUNTY_NAME               0
REGION_NAME               0
POPULATION_GROUP_CODE     0
POPULATION_GROUP_DESC     0
OFFENSE_SUBCAT_ID         0
OFFENSE_NAME              0
OFFENSE_SUBCAT_NAME       0
ACTUAL_COUNT              0
UNFOUNDED_COUNT           0
CLEARED_COUNT             0
JUVENILE_CLEARED_COUNT    0
dtype: int64

In [34]:
data

,DATA_YEAR,ORI,PUB_AGENCY_NAME,PUB_AGENCY_UNIT,AGENCY_TYPE_NAME,STATE_ABBR,STATE_NAME,DIVISION_NAME,COUNTY_NAME,REGION_NAME,POPULATION_GROUP_CODE,POPULATION_GROUP_DESC,OFFENSE_SUBCAT_ID,OFFENSE_NAME,OFFENSE_SUBCAT_NAME,ACTUAL_COUNT,UNFOUNDED_COUNT,CLEARED_COUNT,JUVENILE_CLEARED_COUNT
45,2018,MI3803800,State Police:,Jackson County,State Police,MI,Michigan,East North Central,JACKSON,Midwest,9D,"MSA counties under 10,000",81,Human Trafficking,Commercial Sex Acts,2,0,0,0
46,2019,MI3803800,State Police:,Jackson County,State Police,MI,Michigan,East North Central,JACKSON,Midwest,9D,"MSA counties under 10,000",82,Human Trafficking,Involuntary Servitude,1,0,0,0
47,2020,MI3803800,State Police:,Jackson County,State Police,MI,Michigan,East North Central,JACKSON,Midwest,9D,"MSA counties under 10,000",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
96,2020,MI4104100,State Police:,Kent County,State Police,MI,Michigan,East North Central,KENT,Midwest,9D,"MSA counties under 10,000",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
187,2019,WVWSP4300,State Police:,Romney,State Police,WV,West Virginia,South Atlantic,HAMPSHIRE,South,9D,"MSA counties under 10,000",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4195,2020,VA083SP00,State Police:,Russell County,State Police,VA,Virginia,South Atlantic,RUSSELL,South,8D,"Non-MSA counties under 10,000",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
4196,2020,VA084SP00,State Police:,Scott County,State Police,VA,Virginia,South Atlantic,SCOTT,South,9D,"MSA counties under 10,000",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
4213,2019,MI8208200,State Police:,Wayne County,State Police,MI,Michigan,East North Central,WAYNE,Midwest,9D,"MSA counties under 10,000",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
4214,2020,MI8208200,State Police:,Wayne County,State Police,MI,Michigan,East North Central,WAYNE,Midwest,9D,"MSA counties under 10,000",81,Human Trafficking,Commercial Sex Acts,1,0,0,0
4301,2016,DE303SP00,State Police:,Sussex County,State Police,DE,Delaware,South Atlantic,SUSSEX,South,9A,"MSA counties 100,000 or over",81,Human Trafficking,Commercial Sex Acts,7,0,0,0

In [38]:
fig = px.bar(data[:15], x="DATA_YEAR", y="DIVISION_NAME")
fig.update_layout(
    title='Human Trafficking',
    yaxis=dict(
        title='DIVISION_NAME'
    )
)
fig.show()